security:
  cors:
    allowed-origins:
      - "http://localhost:3000"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed-headers:
      - "*"
    allow-credentials: true

  permit-urls:
    - /register
    - /login
    - /refresh
  deny-urls:
#    - /admin/**
